using System.Text.Json;

namespace ChopItUp.Hub.Hosting;

/// <summary>Emits ready-to-paste MCP client configurations carrying this hub's port and each host's
/// real token. Claude Desktop cannot dial a plain-http loopback remote connector, so it goes through
/// the mcp-remote stdio bridge; Codex reads the same config.toml from the ChatGPT desktop app, the
/// CLI and the IDE extension, and accepts an http://127.0.0.1 URL directly.
///
/// Everything lands under the gitignored data directory. These files hold live tokens, so they are
/// never written anywhere else, and <b>never</b> into <c>%APPDATA%\Claude\claude_desktop_config.json</c>
/// or <c>~/.codex/config.toml</c>: those are the owner's files and the owner pastes into them.</summary>
public static class HostConfigs
{
    public const string FolderName = "host-configs";
    public const string McpRemoteVersion = "0.8.3";

    public static string Write(string dataDir, int port, IReadOnlyDictionary<string, string> tokens)
    {
        var folder = Path.Combine(dataDir, FolderName);
        Directory.CreateDirectory(folder);
        var url = $"http://127.0.0.1:{port}/mcp";
        File.WriteAllText(Path.Combine(folder, "claude-desktop.json"), ClaudeDesktop(url, tokens["claude"]));
        File.WriteAllText(Path.Combine(folder, "codex-config.toml"), Codex(url, tokens["codex"]));
        File.WriteAllText(Path.Combine(folder, "README.md"), Readme(url, port));
        return folder;
    }

    /// <summary>Claude Desktop cannot reach http://localhost as a remote connector, so it spawns
    /// mcp-remote as a local stdio server that proxies to the hub. The header value lives in env
    /// rather than inline: an arg containing a space is mangled on Windows (mcp-remote README).</summary>
    private static string ClaudeDesktop(string url, string token) => JsonSerializer.Serialize(new
    {
        mcpServers = new Dictionary<string, object>
        {
            ["chopitup"] = new
            {
                command = "npx",
                args = new[]
                {
                    "-y", $"mcp-remote@{McpRemoteVersion}", url,
                    "--allow-http", "--transport", "http-only",
                    "--header", "Authorization:${CHOPITUP_TOKEN}",
                },
                env = new Dictionary<string, string> { ["CHOPITUP_TOKEN"] = "Bearer " + token },
            },
        },
    }, new JsonSerializerOptions { WriteIndented = true }) + Environment.NewLine;

    // $$""" (two dollars) so a single brace is literal TOML/shell text and {{expr}} is the
    // interpolation. The emitted file must carry single braces: `{ Authorization = ... }` is TOML
    // inline-table syntax and `${CHOPITUP_TOKEN}` is mcp-remote's env-substitution form.
    private static string Codex(string url, string token) => $$"""
        # Paste into %USERPROFILE%\.codex\config.toml (the ChatGPT desktop Codex surface, the Codex
        # CLI and the IDE extension all read this one file). Restart Codex afterwards.
        [mcp_servers.chopitup]
        url = "{{url}}"
        http_headers = { Authorization = "Bearer {{token}}" }
        startup_timeout_sec = 20
        tool_timeout_sec = 60

        # Alternative if a literal token in this file is unwelcome: set the machine environment
        # variable CHOPITUP_CODEX_TOKEN to the value above (including the word Bearer is NOT needed
        # here) and replace the http_headers line with:
        #   bearer_token_env_var = "CHOPITUP_CODEX_TOKEN"

        # Fallback (grill note R2) if Codex refuses a plain-http URL: run the same mcp-remote bridge
        # Claude Desktop uses, as a stdio server, and delete the url/http_headers block above.
        # [mcp_servers.chopitup]
        # command = "npx"
        # args = ["-y", "mcp-remote@{{McpRemoteVersion}}", "{{url}}", "--allow-http", "--transport", "http-only", "--header", "Authorization:${CHOPITUP_TOKEN}"]
        # [mcp_servers.chopitup.env]
        # CHOPITUP_TOKEN = "Bearer {{token}}"

        """;

    // No Claude Code artifact in M2, deliberately. It would have to reuse the 'claude' token, and
    // read_cursors is keyed (participant_id, room_id) with a stateless transport — two hosts on one
    // identity would share and race one cursor while the participation prompt promises a private
    // one (pass 2, MAJOR-2). Claude Code as a host is M5's job and needs its own participant row,
    // which is a schema change, not a config file.

    private static string Readme(string url, int port) => $"""
        # Host configs for Chop It Up

        Generated by `ChopItUp.Hub --print-config`. Every file here contains a live token: this
        folder lives under the gitignored data directory and must never be copied into the repo,
        a chat, or a screenshot.

        Hub endpoint: {url} (loopback only — nothing outside this machine can reach it).

        | File | Where it goes |
        |------|---------------|
        | `claude-desktop.json` | Merge the `mcpServers` entry into `%APPDATA%\Claude\claude_desktop_config.json`, then fully quit and reopen Claude Desktop. |
        | `codex-config.toml` | Append to `%USERPROFILE%\.codex\config.toml`, then restart Codex. |

        Claude Desktop goes through the `mcp-remote` bridge because its remote connectors are dialled
        from Anthropic's cloud and cannot reach a loopback address; that needs Node on PATH (`npx`).
        If Claude Desktop logs a spawn failure for `npx`, use the Windows-shell form instead:
        `"command": "cmd"` with `"/c"`, `"npx"` in front of the existing arguments. `npx` also
        resolves against the npm registry on every launch, so if you would rather this app not
        depend on the network to start: `npm i -g mcp-remote@{McpRemoteVersion}` once, then change
        `"command"` to `"mcp-remote"` and drop the `-y` and version arguments.

        Claude Code is not configured here. It would have to join as the same `claude` participant
        Claude Desktop uses, and two hosts on one identity share one read cursor. It gets its own
        participant when the autonomous-turns milestone lands.

        This folder is only as private as the directory it sits in — two live bearer tokens with
        no expiry. If other accounts or unattended processes can read this machine's files, they can
        read these.

        Tokens: `ChopItUp.Hub --rotate-token claude` mints a new one and invalidates the old at the
        next hub start. It does not print the token — re-run `--print-config` and re-paste that
        host's file.

        Port {port} is the configured port; if you start the hub with `--port`, regenerate this
        folder so the URLs match.

        ## Restoring a backup

        Every schema migration writes a verified snapshot beside the database first, named
        `chopitup.db.v<old version>.<timestamp>.bak`. To go back to one:

        1. Stop the hub. Confirm no ChopItUp process is running — a live WAL is what makes this
           dangerous.
        2. Delete `chopitup.db`, `chopitup.db-wal` and `chopitup.db-shm`. **All three.** Leaving a
           stale `-wal` beside a restored database lets SQLite replay post-migration writes onto it.
        3. Copy the `.bak` to `chopitup.db` (copy, do not move — keep the snapshot).
        4. Start the hub. It will migrate the restored database forward again, taking a fresh
           snapshot as it goes.

        """;
}
