using System.Net;
using System.Net.Sockets;
using ChopItUp.Core.Memory;
using ChopItUp.Core.Messaging;
using ChopItUp.Core.Model;
using ChopItUp.Core.Storage;
using ChopItUp.Hub.Git;
using ChopItUp.Hub.Mcp;
using ChopItUp.Hub.Memory;
using ChopItUp.Hub.Realtime;
using ChopItUp.Hub.Rooms;
using ChopItUp.Hub.Security;
using ChopItUp.Hub.Skills;
using ChopItUp.Hub.Spawning;
using ChopItUp.Hub.Web;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting.Server;
using Microsoft.AspNetCore.Hosting.Server.Features;
using Microsoft.AspNetCore.SignalR;
using ModelContextProtocol.AspNetCore;

namespace ChopItUp.Hub.Hosting;

public static class HubHost
{
    public static WebApplication Build(HubOptions options, IProcessRunner? processRunner = null, SpawnLimits? limits = null, CliLocator? cliLocator = null, Func<string, MemoryGit>? memoryGit = null, Func<string, GitTrail>? roomGit = null, TimeProvider? clock = null, RunLimits? runLimits = null, IOwnerPeerCheck? ownerPeerCheck = null)
    {
        var hubLock = HubLock.Acquire(options.DataDir);   // first: fail fast if another hub owns this dir
        // A port file that exists while the lock is held must always belong to the hub that holds the
        // lock, never a previous run's. Deleted immediately after the lock is taken;
        // ApplicationStarted below writes the real bound port once it is known.
        try { File.Delete(Path.Combine(options.DataDir, HubPortFile.FileName)); }
        catch (IOException) { /* best-effort: a missing or momentarily-locked file is not fatal here */ }
        try
        {
            var builder = WebApplication.CreateBuilder();
            // The built-in AllowedHosts list-matching is disabled ("*" turns off ASP.NET Core's Host
            // Filtering Middleware) in favour of LoopbackHostFilter below, which answers "is this
            // loopback" by parsing the address rather than by comparing strings: a fixed list rejects
            // Windows PowerShell 5.1's fully-expanded IPv6 Host header
            // ([0000:0000:0000:0000:0000:0000:0000:0001]) even though it names the same address as [::1].
            builder.Configuration["AllowedHosts"] = "*";
            // On Windows `localhost` resolves to ::1 first, so a host configured with a localhost URL
            // never reaches us unless ::1 is actually listening. Guarded on a non-zero port: with port
            // 0 the two families get different ephemeral ports and the single-address assumption
            // breaks. An absent or disabled IPv6 stack is not a reason to fail to start; 127.0.0.1 is
            // the contract and ::1 is the convenience.
            builder.WebHost.ConfigureKestrel(k =>
            {
                k.Listen(IPAddress.Loopback, options.Port);
                if (options.Port != 0 && Socket.OSSupportsIPv6)
                {
                    try { k.Listen(IPAddress.IPv6Loopback, options.Port); }
                    catch (Exception e) when (e is SocketException or InvalidOperationException or NotSupportedException)
                    {
                        Console.Error.WriteLine($"Not listening on [::1]:{options.Port} ({e.Message}); 127.0.0.1 only.");
                    }
                }
            });

            var db = new ChopDb(Path.Combine(options.DataDir, "chopitup.db"));
            db.EnsureDatabase();
            var participants = new ParticipantStore(db);
            // Startup-static, like the tokens: the roster is read once here, and every consumer
            // below (tokens, instructions, tools) sees the same list. Editing rows takes effect at
            // the next hub start.
            var roster = participants.List();
            var tokens = TokenStore.Load(options.DataDir, roster, options.ShellToken);
            // ProcessRunner inherits this process's environment into every spawn; the shell's owner
            // bearer must not ride along. Scrubbed here, before any spawn can exist.
            Environment.SetEnvironmentVariable(HubOptions.ShellTokenEnvVar, null);
            var messages = new MessageStore(db);
            // A host-config file generated by an older build (or hand-edited) may still carry a real
            // bearer. A rewrite failure never stops the hub: a locked file or a deny-write ACL is
            // reported on stderr and in a room note, and the hub keeps serving either way.
            foreach (var outcome in HostConfigs.SweepLiveTokens(options.DataDir, tokens))
            {
                if (outcome.Rewritten)
                {
                    Console.Error.WriteLine($"Replaced a live token in '{outcome.Path}' with {HostConfigs.TokenPlaceholder}.");
                    continue;
                }
                Console.Error.WriteLine($"Could not remove the live token from '{outcome.Path}' ({outcome.Error}). Run --rotate-token <id> for that row and paste the new value in by hand, then fix the file.");
                try
                {
                    messages.Post("general", ChopDb.HubParticipantId,
                        $"'{outcome.Path}' still carries a live credential and could not be rewritten automatically. Run `ChopItUp.Hub --rotate-token <id>` and paste the value it prints over the {HostConfigs.TokenPlaceholder} placeholder yourself.");
                }
                catch (Exception e)
                {
                    Console.Error.WriteLine($"Could not post the host-config warning to 'general': {e.Message}");
                }
            }
            // The memory store lives beside the database; the seed core is written once, the git
            // trail is created lazily by the first approval.
            var memory = new MemoryStore(Path.Combine(options.DataDir, "memory"));
            memory.EnsureLayout();
            // Read on demand, never cached: a skill is a document, not a credential, and
            // --import-skill must take effect without a restart.
            var skills = new SkillStore(Path.Combine(options.DataDir, "skills"), new SkillHashes(db));
            skills.EnsureLayout();

            builder.Services.AddSingleton(db);
            builder.Services.AddSingleton(messages);
            builder.Services.AddSingleton(participants);
            builder.Services.AddSingleton<MessageSignal>();
            builder.Services.AddSingleton(tokens);
            builder.Services.AddSingleton<IReadOnlyList<Participant>>(roster);
            builder.Services.AddSingleton(options);
            builder.Services.AddSingleton(limits ?? SpawnLimits.Default);
            // .NET's own TimeProvider, not a hand-rolled interface, so a run's whole timeline can be
            // driven by a fake clock in tests without waiting on a wall clock (the 8-hour cap).
            var effectiveClock = clock ?? TimeProvider.System;
            builder.Services.AddSingleton(effectiveClock);
            // The runs table and its satellites (schema v8), and the hard-coded caps, exactly as
            // unreachable from inside a room as SpawnLimits.Default above. runLimits is an override for
            // the same reason `limits` (SpawnLimits) is one: tests need a small ceiling and a
            // controllable clock to prove a cap parks a run without waiting out 80 spawns or 8 hours.
            var runs = new RunStore(db);
            builder.Services.AddSingleton(runs);
            builder.Services.AddSingleton(runLimits ?? RunLimits.Default);
            // A stored 'active' run means the hub died, was killed, or was force-stopped while
            // something was driving it. Nothing is driving it in this fresh process, so it must never
            // be left 'active' across a restart. Parked before anything is served: MessageSignal and
            // SpawnerService do not exist yet at this point in Build, so there is nowhere to post a
            // note to, and none is wanted.
            foreach (var stale in runs.ListActive())
                runs.Park(stale.Id, "the hub restarted while this run was active", capSpent: false, effectiveClock.GetUtcNow());
            // One registry, DI-owned: every ProcessRunner child lands in it, and the hub's owner-peer check
            // asks it whether a loopback peer's PID is inside a spawn.
            var jobs = new SpawnJobs();
            builder.Services.AddSingleton(jobs);
            builder.Services.AddSingleton<IProcessRunner>(processRunner ?? new ProcessRunner(jobs));
            // The switch outranks any injected check, so a test can inject an InsideSpawn fake and
            // turn the switch off and observe that the switch wins.
            builder.Services.AddSingleton<IOwnerPeerCheck>(options.OwnerPeerCheck ? (ownerPeerCheck ?? new OwnerPeerCheck(jobs)) : new DisabledOwnerPeerCheck());
            if (!options.OwnerPeerCheck)
                Console.Error.WriteLine("WARNING: --owner-peer-check off: an owner-class credential is accepted from any local process, including a spawn.");
            builder.Services.AddSingleton<CliLocator>(cliLocator ?? (name => CliResolver.Resolve(name)));
            // One gate per room at a time. A singleton so the lock survives regardless of RunTools'
            // own DI lifetime (RunTools, like RoomTools/MemoryTools, holds no state of its own).
            builder.Services.AddSingleton<GateLocks>();
            builder.Services.AddSingleton<SpawnerService>();
            builder.Services.AddHostedService(sp => sp.GetRequiredService<SpawnerService>());
            builder.Services.AddHttpContextAccessor();
            builder.Services.AddSingleton(memory);
            builder.Services.AddSingleton(skills);
            builder.Services.AddSingleton(new MemoryProposalStore(db));
            builder.Services.AddSingleton(new SkillProposalStore(db));
            builder.Services.AddSingleton((memoryGit ?? (root => new MemoryGit(root)))(memory.Root));
            builder.Services.AddSingleton(new RoomTrails(roomGit ?? (dir => new GitTrail(dir))));
            builder.Services.AddSingleton(sp => new RoomDirectories(
                sp.GetRequiredService<MessageStore>(), sp.GetRequiredService<RoomTrails>(), RoomPathRules.ForHub(options.DataDir), options.RoomsRootPath));
            builder.Services.AddSingleton(sp => new ExchangeWorktrees(
                sp.GetRequiredService<MessageStore>(), sp.GetRequiredService<RoomTrails>(), RoomPathRules.ForHub(options.DataDir)));
            builder.Services.AddMcpServer(o => o.ServerInstructions = Participation.Instructions(roster))
                .WithHttpTransport(o => o.SessionMode = HttpServerSessionMode.Stateless)
                .WithTools<RoomTools>().WithTools<MemoryTools>().WithTools<RunTools>().WithTools<SkillTools>();
            builder.Services.AddSignalR();

            var app = builder.Build();
            // The one place a post announces itself outward (see MessageSignal.Posted's doc comment):
            // every path that calls the message-carrying Publish overload (post_message, the web
            // API's post/import) reaches every browser subscribed to that room's SignalR group,
            // regardless of which path stored the message.
            var roomHubContext = app.Services.GetRequiredService<IHubContext<RoomHub>>();
            app.Services.GetRequiredService<MessageSignal>().Posted += message => BroadcastAsync(roomHubContext, message);
            app.Lifetime.ApplicationStopped.Register(hubLock.Dispose);
            // Record the port actually bound, so --print-config emits URLs that match reality. With
            // Port: 0 the real port is only known after the server starts, so this reads the bound
            // address rather than options.Port.
            app.Lifetime.ApplicationStarted.Register(() =>
            {
                var bound = app.Services.GetRequiredService<IServer>().Features.Get<IServerAddressesFeature>()
                    ?.Addresses.Select(a => new Uri(a).Port).FirstOrDefault();
                if (bound is > 0) HubPortFile.Write(options.DataDir, bound.Value);
            });
            // First in the pipeline, ahead of every other check: a caller whose Host header does not
            // name loopback under any spelling never reaches auth or an endpoint.
            app.Use(async (context, next) =>
            {
                if (!LoopbackHostFilter.IsLoopback(context.Request.Host.Value))
                {
                    context.Response.StatusCode = StatusCodes.Status400BadRequest;
                    return;
                }
                await next();
            });
            app.UseMiddleware<BearerTokenMiddleware>();
            app.UseSpaClient(SpaFiles.ResolveWebRoot(options.WebRoot));
            app.MapGet("/health", (ChopDb d, MessageStore s) => Results.Json(new
            {
                ok = true,
                schema = d.GetSchemaVersion(),
                key_usage = s.KeyUsage().Select(r => new { author = r.AuthorId, keyed = r.Keyed, keyless = r.Keyless }),
            }));
            app.MapMcp("/mcp");
            app.MapHub<RoomHub>("/hub/rooms");
            app.MapChatApi();
            app.MapRoomsApi();
            app.MapRolesApi();
            app.MapExchangeApi();
            app.MapRunsApi();
            app.MapMemoryApi();
            app.MapSkillsApi();
            return app;
        }
        catch
        {
            hubLock.Dispose();
            throw;
        }
    }

    /// <summary>Fire-and-forget by design: a stalled or disconnected browser client must never slow
    /// down or fail the post that triggered it. Exceptions are swallowed after logging — nothing here
    /// is retried, and a missed broadcast is recoverable by the client re-reading the room.</summary>
    private static async void BroadcastAsync(IHubContext<RoomHub> hubContext, ChopItUp.Core.Model.Message message)
    {
        try
        {
            await hubContext.Clients.Group(message.RoomId).SendAsync("MessagePosted", new
            {
                message.Id,
                message.RoomId,
                message.AuthorId,
                message.Body,
                message.CreatedAt,
                message.ReplyToId,
                message.Imported,
            });
        }
        catch (Exception e)
        {
            Console.Error.WriteLine($"SignalR broadcast to room '{message.RoomId}' failed: {e.Message}");
        }
    }
}
